### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by kanakiyajay** [mike-allison/jTableScroll#1]
http://mikeallisononline.com/Projects/jquery/jTableScroll/ gives 404

**Comment by mikeallisonJS** [comment]
where did you find that link?
I see: http://mikeallisononline.com/Projects/jTableScroll

**Comment by kanakiyajay** [comment]
Over here:
![jtb](https://cloud.githubusercontent.com/assets/1035423/8024940/887f1cee-0d62-11e5-874a-0596c4d5a34f.png)

**Comment by mikeallisonJS** [comment]
Thanks!
